### PR TITLE
18.2.0

### PR DESCRIPTION
**Pull request by NitzanMordhai**
Signed-off-by: Nitzan Mordechai <nmordech@redhat.com>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @NitzanMordhai! is there a good way to run main's dencoder tests against this before merging?

i noticed that we're also missing the corpus for 17.2.0, so i'm working to generate that as well

**Comment by NitzanMordhai** [comment]
> thanks @NitzanMordhai! is there a good way to run main's dencoder tests against this before merging?
> 
> i noticed that we're also missing the corpus for 17.2.0, so i'm working to generate that as well

@cbodley yes, after you have that submodule update in your main, you can run src/test/encoding/readable.sh script, it will validate the main dencoder against that new version object repository and try to decode them and compare them to find if it is able to decode.

**Comment by cbodley** [comment]
ty, i didn't realize it was a submodule. i pushed https://github.com/ceph/ceph/pull/54735 which points the submodule at this PR to see the checks run. hopefully that's enough to validate this and get it merged?

**Comment by cbodley** [comment]
it would be really nice to have this in place for squid testing

**Comment by NitzanMordhai** [comment]
@neha-ojha @rzarzynski can you please review that?

**Review by neha-ojha — APPROVED** [review]

**Review by rzarzynski — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
anything preventing this?

**Comment by NitzanMordhai** [comment]
@sebastian-philipp i don't think so, since https://github.com/ceph/ceph/pull/54735 was merged already
@cbodley are we ok with merging it?

**Pull request merged**
