### PR TITLE
15.0.0-539-g191ab33faf

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
```
...
skipping unrecognized type utime_t
skipping unrecognized type uuid_d
        /var/ssd/ceph/ceph-object-corpus/archive/15.0.0-539-g191ab33faf/objects/watch_info_t
skipping unrecognized type watch_item_t
passed 7257 tests.
```

tested with https://github.com/ceph/ceph/pull/27704

**Review by liewegas — APPROVED** [review]

**Comment by gregsfortytwo** [comment]
@tchaikov, I'm sure I'm missing something obvious but why doesn't the test understand those types? If it's on purpose, shouldn't we remove them from the corpus so we don't have to try and remember which unrecognized types are okay and which aren't?

**Comment by tchaikov** [comment]
@gregsfortytwo thanks for bring this up! i was so happy to fix the `DENC_DUMP_PRE` macro in ceph/ceph#27704 that i ignored the "skipping unrecognized" messages in the output.

> why doesn't the test understand those types?

because they are not added in `src/tools/ceph-dencoder/type.sh` using `TYPE()` or `TYPE_FEATUREFUL()`.

> If it's on purpose,

i am not sure if it's on purpose. actually, i doubt it. for instance, `utime_t` is used as an on-wire format in multiple places. even we always mark its container types using `TYPE()` or `TYPE_FEATUREFUL()`, does this render it unnecessary to include it in the corpus and in ceph-dencoder?

> shouldn't we remove them from the corpus so we don't have to try and remember which unrecognized types are okay and which aren't?

yeah, i am for this idea -- to remove unnecessary bits. but we need to answer the previous question first, i think.

@neha-ojha @liewegas what do you think?

**Comment by liewegas** [comment]
I'm inclined to leave the objects there as a record of how they encoded in past versions.  The storage isn't scarce and it might be useful in the future.

**Comment by gregsfortytwo** [comment]
Hmm I'm confused about this because I don't see those types every being in types.h (including its previous location), but I guess they can get pulled into the object corpus just by using the macros. So I guess either we can add them to the list or mark them as deliberately excluded somewhere?
Made a PR at https://github.com/ceph/ceph/pull/27804 to see if just adding them passes.

**Pull request merged**
